// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: grpc_chat.proto

package grpcchat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_grpc_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_grpc_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_grpc_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_grpc_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Message) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_grpc_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_grpc_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Amount) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_grpc_chat_proto protoreflect.FileDescriptor

const file_grpc_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc_chat.proto\"\x1a\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"M\n" +
	"\aMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\" \n" +
	"\x06Amount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount2T\n" +
	"\bGrpcChat\x12$\n" +
	"\vGetMessages\x12\a.Amount\x1a\b.Message\"\x000\x01\x12\"\n" +
	"\fSendMessages\x12\x05.Text\x1a\a.Amount\"\x00(\x01B0Z.github.com/TimofeiBoldenkov/grpc-chat/grpcchatb\x06proto3"

var (
	file_grpc_chat_proto_rawDescOnce sync.Once
	file_grpc_chat_proto_rawDescData []byte
)

func file_grpc_chat_proto_rawDescGZIP() []byte {
	file_grpc_chat_proto_rawDescOnce.Do(func() {
		file_grpc_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_chat_proto_rawDesc), len(file_grpc_chat_proto_rawDesc)))
	})
	return file_grpc_chat_proto_rawDescData
}

var file_grpc_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_chat_proto_goTypes = []any{
	(*Text)(nil),    // 0: Text
	(*Message)(nil), // 1: Message
	(*Amount)(nil),  // 2: Amount
}
var file_grpc_chat_proto_depIdxs = []int32{
	2, // 0: GrpcChat.GetMessages:input_type -> Amount
	0, // 1: GrpcChat.SendMessages:input_type -> Text
	1, // 2: GrpcChat.GetMessages:output_type -> Message
	2, // 3: GrpcChat.SendMessages:output_type -> Amount
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_chat_proto_init() }
func file_grpc_chat_proto_init() {
	if File_grpc_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_chat_proto_rawDesc), len(file_grpc_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_chat_proto_goTypes,
		DependencyIndexes: file_grpc_chat_proto_depIdxs,
		MessageInfos:      file_grpc_chat_proto_msgTypes,
	}.Build()
	File_grpc_chat_proto = out.File
	file_grpc_chat_proto_goTypes = nil
	file_grpc_chat_proto_depIdxs = nil
}
